let DATA = [{
    "guid": "edc22f71-9a28-48b7-91dc-2480a2eb6651",
    "action": "Évennements",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Fables de la Fontaine",
    "alternativeHeadline": "Spectacle Compagnie Zdenko",
    "image": "./pics/events/affiche_bestaire_la-fontaine.gif",
    "imageBadge": "",
    "author": "Jean-Claude Audouin",
    "award": "",
    "editor": "Zdenko",
    "genre": "Guitare et chant",
    "keywords": ['guitare', 'chant', 'vidéo'],
    "publisher": "Junipoor",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": " A l'occasion de sa venue au théâtre d’Angoulême, la compagnie Zdenko vous invite vendredi 25 mai 2018 à midi à la représentation de son spectacle : « le bestiaire enchanté de M. La Fontaine ». Une belle occasion de venir en famille découvrir ou redécouvrir les celèbres fables à la mode de Jacques Offenbach, Charles Lecocq et Jean-Claude Audouin.",
    "articleBody": "<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" style=\"color: rgb(0, 0, 0); font-size: 18.6667px; font-family: Helvetica, Arial, sans-serif; width: 1098px; border-collapse: collapse;\"><tbody><tr><td style=\"font-family: arial, sans-serif; margin: 0px; padding: 0cm;\" valign=\"top\"><table align=\"left\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 274px; border-collapse: collapse;\"><tbody><tr><td style=\"margin: 0px; width: 205.55pt; padding: 0cm;\" width=\"274\"><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\">NFOS PRATIQUES<\/span><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 10pt; font-family: Arial, sans-serif; font-weight: normal;\">VENDREDI 25 MAI 2018<\/span><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\">A partir de midi au&nbsp;<strong><span style=\"font-weight: normal;\">THE&Acirc;TRE d&rsquo;ANGOUL&Ecirc;ME<\/span><\/strong><br\/>Avenue des mar&eacute;chaux<br\/>16000 ANGOUL&Ecirc;ME<\/span><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\">&nbsp;<\/span><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\">RESERVATION OBLIGATOIRE<\/span><\/strong><br\/>05 45 38 61 62<br\/>&nbsp;<\/p><\/td><\/tr><\/tbody><\/table><\/td><td style=\"font-family: arial, sans-serif; margin: 0px; width: 22.5pt; padding: 0cm;\" width=\"30\">&nbsp;<\/td><td style=\"font-family: arial, sans-serif; margin: 0px; padding: 0cm;\" valign=\"top\"><table align=\"right\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 255px; border-collapse: collapse;\"><tbody><tr><td style=\"margin: 0px; width: 191.25pt; padding: 0cm;\" width=\"255\">&nbsp;<\/td><\/tr><\/tbody><\/table><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><i><span style=\"font-size: 12pt; font-family: Calibri, sans-serif;\">Compagnie Zdenko<\/span><\/i><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 12pt; font-family: Calibri, sans-serif; font-weight: normal;\">Baryton&nbsp;: Nicolas Rouault<\/span><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 12pt; font-family: Calibri, sans-serif; font-weight: normal;\">Guitare&nbsp;: Jean-Claude Audouin<\/span><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><strong><span style=\"font-size: 12pt; font-family: Calibri, sans-serif; font-weight: normal;\">Dessin&nbsp;: Natacha Sicaud<\/span><\/strong><\/p><p style=\"line-height: 16.5pt; margin: 0px;\"><b><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\">&nbsp;<\/span><\/b><\/p><p style=\"margin: 0px;\"><strong><span style=\"font-size: 10pt; font-family: Arial, sans-serif;\"><a data-saferedirecturl=\"https:\/\/www.google.com\/url?hl=fr&amp;q=http:\/\/www.compagnie-zdenko.com&amp;source=gmail&amp;ust=1526320881453000&amp;usg=AFQjCNH4-uu5S8tX_LU638iDNSXBepsMEA\" href=\"http:\/\/www.compagnie-zdenko.com\/\" style=\"color: rgb(17, 85, 204);\" target=\"_blank\">www.compagnie-zdenko.com<\/a><\/span><\/strong><\/p><\/td><\/tr><\/tbody><\/table><p style=\"color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; margin: 0px; line-height: 16.5pt;\">&nbsp;<\/p><p style=\"color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; margin: 0px; line-height: 16.5pt;\">La Compagnie Zdenko re&ccedil;oit le soutien de la DRAC Nouvelle Aquitaine, du Conseil D&eacute;partemental de la Charente, de la communaut&eacute; de communes du GrandAngoul&ecirc;me et du Cr&eacute;dit Mutuel du Sud-Ouest.<\/p><p style=\"color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; margin: 0px; line-height: 16.5pt;\">&nbsp;<\/p><p style=\"color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; margin: 0px; line-height: 16.5pt;\">Elle b&eacute;n&eacute;ficie du label europ&eacute;en du patrimoine culturel<\/p>",
    "wordcount": 276
  },
  {
    "guid": "edc22f71-9a28-48b7-91dc-2480a2eb6651",
    "action": "Cours",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Cours de guitare et de composition",
    "alternativeHeadline": "Apprentissage et préparations",
    "image": "./pics/left-hand.jpg",
    "imageBadge": "  <a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\"\r\n\r\n     href=\"https:\/\/unsplash.com\/@scottgruber?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\"\r\n     target=\"_blank\"\r\n     rel=\"noopener noreferrer\"\r\n     title=\"Download free do whatever you want high-resolution photos from Scott Gruber\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">Scott Gruber<\/span><\/a>",
    "author": "Ramos Waller",
    "award": "Best article ever written",
    "editor": "Musix",
    "genre": "eu",
    "keywords": "excepteur esse et Lorem occaecat",
    "publisher": "Junipoor",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Tempor consequat ut laborum dolor ipsum id ullamco sit consectetur laborum magna exercitation eu.",
    "articleBody": "Et id eiusmod excepteur sunt nulla adipisicing irure tempor esse non mollit ad amet consequat. Exercitation sint mollit reprehenderit consectetur. Minim cillum non eiusmod officia dolore. Do amet ea culpa dolor ipsum voluptate dolore duis duis magna ea.\n\nEt est do cillum exercitation aliqua voluptate velit duis qui do velit commodo id esse. Eu ea occaecat deserunt sunt reprehenderit aliquip enim Lorem tempor magna labore esse. Sit deserunt magna id dolore proident anim sit Lorem cupidatat aliquip reprehenderit. Ex reprehenderit cillum officia duis proident commodo mollit do adipisicing. Voluptate dolor sit dolore ad aliquip irure deserunt culpa elit aliqua cupidatat.\n\nMagna dolore sunt elit eu ex cillum id id incididunt. Elit cillum velit non sit consequat commodo ut ullamco nisi excepteur do veniam. Quis deserunt anim ex est anim ex Lorem cupidatat aliquip deserunt non esse. Et tempor labore laboris eu id quis eu aliqua deserunt elit cillum. Mollit nulla esse pariatur sunt amet ex Lorem elit excepteur fugiat nostrud aliquip. Officia ad ipsum ad qui dolore eiusmod in id id incididunt veniam culpa. Consectetur enim ut tempor amet nisi qui sint magna magna ullamco veniam ea.\n\nLorem dolore consectetur excepteur voluptate. Nulla ut occaecat minim dolore in ea aliqua laborum elit. Laborum magna consequat consectetur pariatur qui.\n\nNon consectetur aute in adipisicing cupidatat mollit laboris esse ex aliqua cupidatat esse quis ut. Proident exercitation Lorem excepteur voluptate voluptate et sint incididunt elit nulla. Excepteur enim ex duis minim tempor ex aute voluptate ipsum enim aliquip. Proident sit excepteur cupidatat voluptate dolore. Mollit irure sunt cupidatat esse proident. Nisi mollit consequat eu magna duis qui. Ullamco sint enim eiusmod ipsum voluptate id.",
    "wordcount": 276
  },
  {
    "guid": "53edae3c-77fe-4b82-ba60-f4b2325f16be",
    "action": "Contact",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Contactez moi par mail",
    "alternativeHeadline": "",
    "image": "./pics/contact.jpg",
    "imageBadge": "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https:\/\/unsplash.com\/@alvaroserrano?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from \u00C1lvaro Serrano\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">\u00C1lvaro Serrano<\/span><\/a>",
    "author": "Raquel Norris",
    "award": "Best article ever written",
    "editor": "Boilicon",
    "genre": "adipisicing",
    "keywords": "ullamco duis laboris commodo deserunt",
    "publisher": "Moreganic",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Aliquip officia dolor ut duis laborum sint sunt pariatur.",
    "articleBody": "Nulla aliqua commodo ullamco ut. Id nisi sit nulla veniam dolor cillum voluptate id pariatur enim consectetur culpa sint. Laborum reprehenderit voluptate nisi proident pariatur.\n\nEnim anim reprehenderit non Lorem ea nulla consequat. Nostrud adipisicing enim magna ut excepteur occaecat cupidatat ullamco do eu. Adipisicing labore non et enim elit laborum commodo do laboris ipsum eiusmod nulla. Anim officia duis consequat esse quis culpa tempor elit. Ipsum exercitation ad irure commodo. Et mollit laborum enim ipsum et in minim aute adipisicing ex cupidatat.\n\nPariatur duis officia elit magna. Sunt reprehenderit pariatur exercitation laboris velit consectetur veniam amet non quis aliqua. Reprehenderit proident id magna aliqua est ad sint incididunt ut dolor velit. Sint adipisicing dolore in aliqua anim ea excepteur magna cillum ex proident. Laborum ullamco adipisicing dolor duis dolore ut eiusmod minim excepteur. Et ipsum laboris pariatur exercitation eu.\n\nSint duis magna elit magna nostrud. Laboris ea officia voluptate commodo. Incididunt veniam aliquip ad fugiat. Fugiat minim nulla voluptate consequat dolor aliqua. Officia aute duis tempor duis nisi enim incididunt eu sunt veniam elit ullamco nostrud excepteur.\n\nAmet velit anim id non ut aliqua ipsum nulla deserunt excepteur. Ex pariatur pariatur sint incididunt eu esse enim est elit. Proident nostrud do Lorem elit sunt velit commodo culpa sit aliqua consequat. Qui enim tempor ex velit esse ad ullamco est adipisicing consectetur. Pariatur exercitation esse enim officia culpa nostrud et culpa sit aute. Commodo laboris adipisicing exercitation id id culpa ullamco ea et ex nisi.",
    "wordcount": 249
  },
  {
    "guid": "65daa3c2-ec1f-4a8d-97d3-0418f4bc0944",
    "action": "Biographie",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Expériences et références bibliographiques",
    "alternativeHeadline": "Medias et publications",
    "image": "./pics/biographie.jpg",
    "imageBadge": "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https:\/\/unsplash.com\/@rawpixel?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from rawpixel\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">rawpixel<\/span><\/a>",
    "author": "Bruce Crane",
    "award": "Best article ever written",
    "editor": "Deepends",
    "genre": "Lorem",
    "keywords": "exercitation excepteur ad adipisicing duis",
    "publisher": "Cedward",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Cupidatat velit laborum amet ex ad sunt in ullamco cupidatat qui consectetur veniam sit.",
    "articleBody": "Esse ut culpa nostrud aute eiusmod fugiat commodo qui pariatur labore labore. Ea minim dolor ullamco amet non sunt amet. Officia labore commodo mollit aliquip qui mollit sint elit culpa anim labore quis quis amet. Eu do tempor dolor cupidatat exercitation reprehenderit. Reprehenderit sit voluptate aliquip amet pariatur cillum velit velit duis velit ullamco.\n\nAute cupidatat ex esse consequat aute ullamco fugiat. Proident tempor et nostrud laborum sunt pariatur deserunt elit pariatur. Magna exercitation ea incididunt aute. Nulla ut nisi duis amet sint labore fugiat irure aute nulla voluptate nulla.\n\nReprehenderit id Lorem minim reprehenderit excepteur occaecat ipsum veniam eiusmod occaecat voluptate. Sint sunt commodo duis consequat eiusmod ea do magna adipisicing consequat incididunt adipisicing in. Ut esse consectetur deserunt nostrud sunt ullamco nulla aliquip tempor. Mollit nulla elit excepteur mollit mollit eu. Officia esse et officia labore pariatur ut. Pariatur nisi enim do esse ad reprehenderit est sit aliquip.\n\nProident sunt magna ut qui pariatur aliqua. Consectetur duis ullamco irure in adipisicing. Duis tempor proident nostrud amet consectetur eiusmod enim excepteur commodo fugiat esse velit non irure. Aliquip duis qui id ea ex ex quis eu nulla aliqua. Ipsum nostrud sunt irure quis magna sit. Laborum duis irure non irure. Culpa ea enim officia laborum adipisicing commodo voluptate eu pariatur officia.\n\nCupidatat dolor velit eiusmod laborum dolor deserunt nisi ex laborum do. Labore irure qui nisi esse Lorem. Velit quis qui non velit cupidatat nulla sunt laboris fugiat elit sint reprehenderit. Enim proident consectetur eiusmod aliquip exercitation occaecat cupidatat id Lorem aliqua veniam sit excepteur fugiat. Eu ex pariatur laborum ex ad reprehenderit dolore magna amet aliquip aliqua sint. In dolore eiusmod commodo est. Occaecat incididunt aliqua do pariatur in veniam.",
    "wordcount": 286
  },
  {
    "guid": "4fb8160b-b397-4289-8a27-a02947123851",
    "action": "Liens",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Liens",
    "alternativeHeadline": "Redirection vers les sites amis",
    "image": "./pics/liens.jpg",
    "imageBadge": "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https:\/\/unsplash.com\/@spmphoto?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from Sean Patrick Murphy\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">Sean Patrick Murphy<\/span><\/a>",
    "author": "Olive Graves",
    "award": "Best article ever written",
    "editor": "Translink",
    "genre": "incididunt",
    "keywords": "occaecat occaecat sint ad nisi",
    "publisher": "Anarco",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Ut anim anim consectetur est est.",
    "articleBody": "Ut eu dolor voluptate cillum nisi. Ullamco tempor deserunt non duis sunt fugiat ut. Officia commodo excepteur nostrud eu ea veniam elit cupidatat nostrud dolor culpa ipsum aute.\n\nUt et id tempor voluptate et proident aliqua aliqua amet. Labore in dolore pariatur ipsum esse incididunt veniam reprehenderit excepteur. Deserunt elit amet excepteur quis ex ut sint cupidatat consectetur magna.\n\nAute amet enim tempor exercitation nulla Lorem. Culpa occaecat cupidatat sunt ipsum velit enim duis cupidatat Lorem. Amet esse labore in ullamco veniam.\n\nCulpa elit adipisicing ipsum enim id culpa. Laborum aute quis et Lorem magna magna dolore. Occaecat non laboris ea amet ea qui mollit fugiat eu. Lorem ipsum cillum nostrud sit sint et in consectetur fugiat esse. Tempor id Lorem ea anim esse labore officia do est non consequat. Adipisicing pariatur laborum reprehenderit laborum minim. Do pariatur consectetur minim quis ut adipisicing.\n\nOccaecat consequat fugiat consectetur ipsum consequat ea pariatur adipisicing. Lorem fugiat eu ex ut incididunt laboris aute velit ex aliquip mollit. In qui et Lorem magna aute esse non consequat et consectetur non. Deserunt sit veniam adipisicing in id reprehenderit laboris incididunt velit et eu voluptate.",
    "wordcount": 193
  },
  {
    "guid": "566ddda4-df18-4568-8355-de31645ff820",
    "action": "Guitare",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Publications pour guitare",
    "alternativeHeadline": "Oeuvres originales et arrangements",
    "image": "./pics/rosace.jpg",
    "imageBadge": "  <a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\"\r\n\r\n     href=\"https:\/\/unsplash.com\/@shootlefty?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\"\r\n     target=\"_blank\"\r\n     rel=\"noopener noreferrer\"\r\n     title=\"Download free do whatever you want high-resolution photos from Vince Gaspar\">\r\n     <span style=\"display:inline-block;padding:2px 3px;\">\r\n       <svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\">\r\n         <title>unsplash-logo<\/title>\r\n         <path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\">\r\n       <\/path>\r\n     <\/svg>\r\n   <\/span>\r\n   <span style=\"display:inline-block;padding:2px 3px;\">Vince Gaspar<\/span>\r\n <\/a>",
    "author": "Maritza Moses",
    "award": "Best article ever written",
    "editor": "Pushcart",
    "genre": "aute",
    "keywords": "dolor excepteur culpa quis ad",
    "publisher": "Schoolio",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Minim veniam minim cupidatat commodo.",
    "articleBody": "Eiusmod aliqua aute deserunt ullamco. Deserunt duis duis culpa mollit commodo qui ullamco in pariatur consectetur magna enim velit. Voluptate tempor aliqua exercitation Lorem labore dolore excepteur ipsum irure irure esse. Veniam aute magna occaecat cupidatat est occaecat amet nostrud incididunt.\n\nSint anim labore aute ex do labore duis. Amet proident incididunt dolore nulla ad non eiusmod minim labore excepteur magna eiusmod eu. Tempor nulla do velit mollit aute nulla. Laboris laborum culpa laboris labore non in sint.\n\nFugiat esse Lorem adipisicing mollit Lorem aliqua voluptate consectetur esse culpa reprehenderit ullamco id. Incididunt Lorem magna est nisi ut adipisicing sint nisi exercitation enim. Non nulla nulla aliquip minim aliqua proident aliqua cupidatat excepteur tempor anim cillum mollit culpa. Commodo proident tempor et id in proident ad incididunt. Do aute cupidatat in magna occaecat laborum veniam.\n\nEnim qui duis dolore dolor aliquip. Laboris aliqua Lorem nulla nisi ea nulla nulla voluptate irure non qui et sint. Quis officia elit ullamco velit adipisicing voluptate aliqua occaecat exercitation dolor dolor adipisicing. Fugiat laboris eu pariatur nostrud ex et fugiat occaecat exercitation. Ut sunt Lorem anim quis velit nostrud culpa duis nisi veniam esse consectetur.\n\nOfficia duis aute occaecat excepteur sint et irure cupidatat dolore irure. Deserunt labore occaecat pariatur sint cupidatat quis occaecat et in incididunt exercitation deserunt et. Eu sint magna incididunt anim in aliquip consequat. Ex est adipisicing ad eu nulla enim est pariatur fugiat tempor cupidatat nisi consectetur. Consectetur enim enim incididunt laboris magna adipisicing ad consectetur mollit magna ullamco adipisicing quis fugiat. Dolore est enim occaecat id. Culpa excepteur ut ut mollit et.",
    "wordcount": 268
  },
  {
    "guid": "48e8cff3-e21e-4957-8d39-c6ff4216e0ad",
    "action": "Chant choral",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Publications pour chant choral",
    "alternativeHeadline": "Oeuvres originales et arrangements",
    "image": "./pics/chorale.jpg",
    "imageBadge": "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https:\/\/unsplash.com\/@benwhitephotography?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from Ben White\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">Ben White<\/span><\/a>",
    "author": "Sellers Vargas",
    "award": "Best article ever written",
    "editor": "Krog",
    "genre": "adipisicing",
    "keywords": "aliquip id labore nisi sunt",
    "publisher": "Corepan",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Irure consequat velit sit dolor magna aute culpa commodo dolor incididunt esse.",
    "articleBody": "Eu elit eu quis cupidatat tempor sint est est ea officia. Velit ea anim non aute sunt quis magna eiusmod minim magna officia. Eiusmod consequat officia velit ea est. Lorem enim qui proident pariatur consectetur. Sit laboris cupidatat Lorem cillum enim minim deserunt quis laboris exercitation commodo. Amet occaecat laboris veniam tempor adipisicing quis ullamco. Sint Lorem est ea magna deserunt.\n\nEt dolore ipsum irure proident proident enim esse. Non ex nostrud deserunt duis elit elit anim minim cillum elit eu. Consequat quis reprehenderit nulla irure non elit nostrud anim reprehenderit elit Lorem ipsum in sunt. Consectetur velit aliqua anim minim non consequat veniam tempor ea amet. Ad excepteur ut reprehenderit qui minim voluptate officia sint amet veniam nostrud dolor laborum pariatur. Lorem anim officia veniam eu ullamco aliqua.\n\nExcepteur amet proident et est reprehenderit exercitation minim sint. Irure aute dolor nulla pariatur est ipsum minim. Cillum eiusmod nisi in culpa sunt commodo reprehenderit aute irure deserunt irure amet incididunt. Quis mollit ullamco deserunt anim exercitation est sit ullamco minim veniam id duis duis. Aliquip sit dolore pariatur nisi proident aliqua ad ut. Incididunt irure laboris consectetur adipisicing duis ullamco incididunt id commodo magna. Id qui do fugiat mollit sint.\n\nAliquip eu mollit adipisicing quis velit consequat occaecat adipisicing dolor. Quis non elit culpa sit duis Lorem. Nostrud esse veniam minim incididunt elit deserunt exercitation excepteur cupidatat. Reprehenderit cupidatat quis veniam aliqua sint ut amet deserunt Lorem aute ipsum ullamco culpa. Incididunt laboris eiusmod laboris consectetur ea ullamco incididunt aliquip deserunt commodo cupidatat non exercitation. Exercitation dolor labore dolor exercitation magna ad sit esse.\n\nDolore Lorem officia culpa non eiusmod laborum. Cillum eiusmod esse in do. Voluptate velit voluptate mollit et. Fugiat cupidatat anim aute enim culpa adipisicing dolor. Id nulla eu officia dolore culpa do ad eu consequat.",
    "wordcount": 303
  },
  {
    "guid": "adf62224-3d51-46f7-918d-e4d45d43b590",
    "action": "Compositions",
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Autres compositions",
    "alternativeHeadline": "Pièces pour ensembles",
    "image": "./pics/composition.jpg",
    "imageBadge": "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https:\/\/unsplash.com\/@dtopkin1?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from Dayne Topkin\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title>unsplash-logo<\/title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"><\/path><\/svg><\/span><span style=\"display:inline-block;padding:2px 3px;\">Dayne Topkin<\/span><\/a>",
    "author": "Fran Doyle",
    "award": "Best article ever written",
    "editor": "Isonus",
    "genre": "laborum",
    "keywords": "nostrud ex sit dolore esse",
    "publisher": "Solgan",
    "url": "http://www.example.com",
    "datePublished": "2015-09-20",
    "dateCreated": "2015-09-20",
    "dateModified": "2015-09-20",
    "description": "Fugiat excepteur dolore incididunt aliqua nisi mollit commodo officia dolore incididunt.",
    "articleBody": "Culpa laboris ullamco dolor ut nostrud sit sunt veniam excepteur incididunt irure adipisicing exercitation laborum. Aute ut laborum nisi nostrud commodo magna ipsum esse dolore enim exercitation. Adipisicing adipisicing nostrud deserunt nulla. Laboris mollit ad ut et cillum aute eu. Sint irure reprehenderit mollit voluptate sint consequat occaecat in minim officia reprehenderit nulla aute. Officia nulla esse magna ad non officia ipsum laborum ad elit.\n\nIncididunt mollit elit qui ullamco dolor esse labore laboris laboris. Nisi voluptate ullamco ut amet amet cillum enim consequat tempor exercitation culpa et sunt. Voluptate veniam pariatur aliqua Lorem veniam.\n\nDolore et aliqua irure consequat dolor deserunt. Laboris eu fugiat eu ex. Proident incididunt do laborum sit duis aliqua deserunt ad anim do cupidatat. Pariatur elit laborum consectetur est officia laborum laborum excepteur aute ullamco in Lorem.\n\nQui aute aute anim ut nisi excepteur sit excepteur. Sint nulla nisi ipsum do eiusmod voluptate proident adipisicing non veniam mollit exercitation. Veniam culpa aliquip labore non nisi cillum ea ea labore sunt commodo nostrud. Reprehenderit aute nisi enim nostrud irure aute cillum commodo ea.\n\nDolore sint do consequat tempor irure in ullamco ex sint pariatur nisi. Sunt nulla sunt laborum eiusmod ad culpa eiusmod excepteur proident proident mollit elit. Aute tempor eu nostrud exercitation laboris adipisicing reprehenderit id veniam nisi fugiat excepteur in laboris. Veniam Lorem non laboris pariatur id ad nisi deserunt fugiat. Id qui consectetur fugiat magna anim in elit elit irure.",
    "wordcount": 241
  }
]